<!DOCTYPE html>
<html>
<head>
    <title>Patients Export - {{ date('Y-m-d') }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { color: #333; margin-bottom: 5px; }
        .header p { color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f8f9fa; border: 1px solid #dee2e6; padding: 10px; text-align: left; }
        td { border: 1px solid #dee2e6; padding: 8px; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Patients List</h1>
        <p>Generated on {{ date('F d, Y H:i:s') }}</p>
        <p>Total Patients: {{ count($patients) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Date of Birth</th>
                <th>Gender</th>
                <th>Blood Group</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($patients as $patient)
            <tr>
                <td>{{ $patient->id }}</td>
                <td>{{ $patient->name }}</td>
                <td>{{ $patient->email }}</td>
                <td>{{ $patient->phone ?? 'N/A' }}</td>
                <td>{{ $patient->date_of_birth ? date('Y-m-d', strtotime($patient->date_of_birth)) : 'N/A' }}</td>
                <td>{{ $patient->gender ?? 'N/A' }}</td>
                <td>{{ $patient->blood_group ?? 'N/A' }}</td>
                <td>{{ $patient->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ Auth::user()->name }} ({{ Auth::user()->role->name }})</p>
        <p>&copy; {{ date('Y') }} Hospital Management System</p>
    </div>
</body>
</html>